language: ruby
rvm:
  - 2.4.5
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/travisdatabase.yml config/database.yml
  - bundle exec rake db:migrate
  - bundle exec rubocop
services:
  - redis-server
